@ECHO OFF

SET USE_WIN_SDK=10.0.14393.0
::SET USE_WIN_SDK_FULL_PATH=

SET BINARIES_DOWNLOAD_REPO_URL=https://github.com/ortclib/ortc-binaries.git
SET BINARIES_DOWNLOAD_REPO_BRANCH=master

::SET BINARIES_DOWNLOAD_URL=192.168.1.12/libs/libOrtc.dylib